name: Deploy Safe Harbor

on:
  workflow_dispatch:
    inputs:
      rpc_url:
        description: "RPC URL for deployment"
        required: true
        type: string
      broadcast:
        description: "Include --broadcast flag"
        required: true
        default: false
        type: boolean

jobs:
  deploy:
    name: Deploy Registry V2
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.rpc_url != '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Deploy Registry V2
        run: forge script DeployRegistryV2 --rpc-url ${{ github.event.inputs.rpc_url }} ${{ github.event.inputs.broadcast == 'true' && '--broadcast' || '' }} --verify --retries 50
        working-directory: registry-contracts
        env:
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          REGISTRY_DEPLOYER_PRIVATE_KEY: ${{ secrets.REGISTRY_DEPLOYER_PRIVATE_KEY }}
